version: 2

sources:
  - name: raw_bike_traffic
    description: "Données brutes issues"
    database: BIKE_MOBILITY
    schema: RAW_BIKE_TRAFFIC
    tables:
      - name: EVENT 
        description: "Enregistrements horaires bruts des compteurs vélos de la ville de Paris."
        columns:
          - name: ID_COMPTEUR
            description: "Identifiant technique du compteur vélo."
            tests:
              - not_null
          - name: DATE
            description: "Horodatage ISO de l'heure de comptage."
            tests:
              - not_null
          - name: SUM_COUNTS
            description: "Nombre total de vélos comptabilisés sur l'heure."
            tests:
              - not_null