name: Post bike traffic to fivetran webhook

on:
  push:
    branches:
      - main
  workflow_dispatch:
  #schedule:
    #- cron: '00 06 * * *'
jobs:
  run-ingestion:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code du dépôt
        uses: actions/checkout@v4

      - name: Configurer l'environnement Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          pip install requests

      - name: Exécuter le script d'ingestion
        env:
          FIVETRAN_WEBHOOK_URL: ${{ secrets.FIVETRAN_WEBHOOK_URL }}
        run: |
          python scripts/extract_and_push.py