name: Ingest Paris Bike Traffic

on:
  push:
    branches:
      - main  # Déclenche à chaque mise à jour du code
  workflow_dispatch:  # Garde ce bouton pour pouvoir lancer le script manuellement
  schedule:
    # "Au minute 0, à 4 heures du matin (UTC), chaque jour"
    # Cela correspond à 06:00 heure d'été à Paris (05:00 en heure d'hiver)
    - cron: '0 4 * * *'
jobs:
  run-ingestion:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code du dépôt
        uses: actions/checkout@v4

      - name: Configurer l'environnement Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          pip install requests

      - name: Exécuter le script d'ingestion
        env:
          FIVETRAN_WEBHOOK_URL: ${{ secrets.FIVETRAN_WEBHOOK_URL }}
        run: |
          python scripts/extract_and_push.py